// Code generated by protoc-gen-go. DO NOT EDIT.
// source: object.proto

package lm_object

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type People_PeopleType int32

const (
	People_INTERNAL People_PeopleType = 0
	People_EXTERNAL People_PeopleType = 1
	People_RUS      People_PeopleType = 3
	People_HR       People_PeopleType = 4
)

var People_PeopleType_name = map[int32]string{
	0: "INTERNAL",
	1: "EXTERNAL",
	3: "RUS",
	4: "HR",
}

var People_PeopleType_value = map[string]int32{
	"INTERNAL": 0,
	"EXTERNAL": 1,
	"RUS":      3,
	"HR":       4,
}

func (x People_PeopleType) String() string {
	return proto.EnumName(People_PeopleType_name, int32(x))
}

func (People_PeopleType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41d48463eef19a5f, []int{1, 0}
}

type Mission struct {
	Id                string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Institution       *Mission_Institution `protobuf:"bytes,2,opt,name=institution,proto3" json:"institution,omitempty"`
	Service           string               `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	BackLink          string               `protobuf:"bytes,4,opt,name=back_link,json=backLink,proto3" json:"back_link,omitempty"`
	AcceptedBackLink  string               `protobuf:"bytes,5,opt,name=accepted_back_link,json=acceptedBackLink,proto3" json:"accepted_back_link,omitempty"`
	RefusedBackLink   string               `protobuf:"bytes,6,opt,name=refused_back_link,json=refusedBackLink,proto3" json:"refused_back_link,omitempty"`
	Motive            string               `protobuf:"bytes,7,opt,name=motive,proto3" json:"motive,omitempty"`
	Reason            string               `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	Requester         *People              `protobuf:"bytes,9,opt,name=requester,proto3" json:"requester,omitempty"`
	ValidationComment string               `protobuf:"bytes,10,opt,name=validation_comment,json=validationComment,proto3" json:"validation_comment,omitempty"`
	// Types that are valid to be assigned to Content:
	//	*Mission_TimeSlotsWithSelected_
	Content              isMission_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Mission) Reset()         { *m = Mission{} }
func (m *Mission) String() string { return proto.CompactTextString(m) }
func (*Mission) ProtoMessage()    {}
func (*Mission) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d48463eef19a5f, []int{0}
}

func (m *Mission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mission.Unmarshal(m, b)
}
func (m *Mission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mission.Marshal(b, m, deterministic)
}
func (m *Mission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mission.Merge(m, src)
}
func (m *Mission) XXX_Size() int {
	return xxx_messageInfo_Mission.Size(m)
}
func (m *Mission) XXX_DiscardUnknown() {
	xxx_messageInfo_Mission.DiscardUnknown(m)
}

var xxx_messageInfo_Mission proto.InternalMessageInfo

func (m *Mission) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Mission) GetInstitution() *Mission_Institution {
	if m != nil {
		return m.Institution
	}
	return nil
}

func (m *Mission) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *Mission) GetBackLink() string {
	if m != nil {
		return m.BackLink
	}
	return ""
}

func (m *Mission) GetAcceptedBackLink() string {
	if m != nil {
		return m.AcceptedBackLink
	}
	return ""
}

func (m *Mission) GetRefusedBackLink() string {
	if m != nil {
		return m.RefusedBackLink
	}
	return ""
}

func (m *Mission) GetMotive() string {
	if m != nil {
		return m.Motive
	}
	return ""
}

func (m *Mission) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Mission) GetRequester() *People {
	if m != nil {
		return m.Requester
	}
	return nil
}

func (m *Mission) GetValidationComment() string {
	if m != nil {
		return m.ValidationComment
	}
	return ""
}

type isMission_Content interface {
	isMission_Content()
}

type Mission_TimeSlotsWithSelected_ struct {
	TimeSlotsWithSelected *Mission_TimeSlotsWithSelected `protobuf:"bytes,12,opt,name=time_slots_with_selected,json=timeSlotsWithSelected,proto3,oneof"`
}

func (*Mission_TimeSlotsWithSelected_) isMission_Content() {}

func (m *Mission) GetContent() isMission_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Mission) GetTimeSlotsWithSelected() *Mission_TimeSlotsWithSelected {
	if x, ok := m.GetContent().(*Mission_TimeSlotsWithSelected_); ok {
		return x.TimeSlotsWithSelected
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Mission) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Mission_TimeSlotsWithSelected_)(nil),
	}
}

type Mission_Institution struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	SmsActive            bool     `protobuf:"varint,3,opt,name=sms_active,json=smsActive,proto3" json:"sms_active,omitempty"`
	SmsPrice             float32  `protobuf:"fixed32,4,opt,name=sms_price,json=smsPrice,proto3" json:"sms_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mission_Institution) Reset()         { *m = Mission_Institution{} }
func (m *Mission_Institution) String() string { return proto.CompactTextString(m) }
func (*Mission_Institution) ProtoMessage()    {}
func (*Mission_Institution) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d48463eef19a5f, []int{0, 0}
}

func (m *Mission_Institution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mission_Institution.Unmarshal(m, b)
}
func (m *Mission_Institution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mission_Institution.Marshal(b, m, deterministic)
}
func (m *Mission_Institution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mission_Institution.Merge(m, src)
}
func (m *Mission_Institution) XXX_Size() int {
	return xxx_messageInfo_Mission_Institution.Size(m)
}
func (m *Mission_Institution) XXX_DiscardUnknown() {
	xxx_messageInfo_Mission_Institution.DiscardUnknown(m)
}

var xxx_messageInfo_Mission_Institution proto.InternalMessageInfo

func (m *Mission_Institution) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Mission_Institution) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Mission_Institution) GetSmsActive() bool {
	if m != nil {
		return m.SmsActive
	}
	return false
}

func (m *Mission_Institution) GetSmsPrice() float32 {
	if m != nil {
		return m.SmsPrice
	}
	return 0
}

type Mission_TimeSlot struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Start                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	Stop                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=stop,proto3" json:"stop,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Mission_TimeSlot) Reset()         { *m = Mission_TimeSlot{} }
func (m *Mission_TimeSlot) String() string { return proto.CompactTextString(m) }
func (*Mission_TimeSlot) ProtoMessage()    {}
func (*Mission_TimeSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d48463eef19a5f, []int{0, 1}
}

func (m *Mission_TimeSlot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mission_TimeSlot.Unmarshal(m, b)
}
func (m *Mission_TimeSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mission_TimeSlot.Marshal(b, m, deterministic)
}
func (m *Mission_TimeSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mission_TimeSlot.Merge(m, src)
}
func (m *Mission_TimeSlot) XXX_Size() int {
	return xxx_messageInfo_Mission_TimeSlot.Size(m)
}
func (m *Mission_TimeSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_Mission_TimeSlot.DiscardUnknown(m)
}

var xxx_messageInfo_Mission_TimeSlot proto.InternalMessageInfo

func (m *Mission_TimeSlot) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Mission_TimeSlot) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Mission_TimeSlot) GetStop() *timestamp.Timestamp {
	if m != nil {
		return m.Stop
	}
	return nil
}

type Mission_TimeSlotsWithSelected struct {
	TimeSlots            []*Mission_TimeSlot `protobuf:"bytes,1,rep,name=time_slots,json=timeSlots,proto3" json:"time_slots,omitempty"`
	Selected             *People             `protobuf:"bytes,2,opt,name=selected,proto3" json:"selected,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Mission_TimeSlotsWithSelected) Reset()         { *m = Mission_TimeSlotsWithSelected{} }
func (m *Mission_TimeSlotsWithSelected) String() string { return proto.CompactTextString(m) }
func (*Mission_TimeSlotsWithSelected) ProtoMessage()    {}
func (*Mission_TimeSlotsWithSelected) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d48463eef19a5f, []int{0, 2}
}

func (m *Mission_TimeSlotsWithSelected) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mission_TimeSlotsWithSelected.Unmarshal(m, b)
}
func (m *Mission_TimeSlotsWithSelected) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mission_TimeSlotsWithSelected.Marshal(b, m, deterministic)
}
func (m *Mission_TimeSlotsWithSelected) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mission_TimeSlotsWithSelected.Merge(m, src)
}
func (m *Mission_TimeSlotsWithSelected) XXX_Size() int {
	return xxx_messageInfo_Mission_TimeSlotsWithSelected.Size(m)
}
func (m *Mission_TimeSlotsWithSelected) XXX_DiscardUnknown() {
	xxx_messageInfo_Mission_TimeSlotsWithSelected.DiscardUnknown(m)
}

var xxx_messageInfo_Mission_TimeSlotsWithSelected proto.InternalMessageInfo

func (m *Mission_TimeSlotsWithSelected) GetTimeSlots() []*Mission_TimeSlot {
	if m != nil {
		return m.TimeSlots
	}
	return nil
}

func (m *Mission_TimeSlotsWithSelected) GetSelected() *People {
	if m != nil {
		return m.Selected
	}
	return nil
}

type People struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 People_PeopleType `protobuf:"varint,2,opt,name=type,proto3,enum=lm.object.People_PeopleType" json:"type,omitempty"`
	FirstName            string            `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string            `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string            `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string            `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *People) Reset()         { *m = People{} }
func (m *People) String() string { return proto.CompactTextString(m) }
func (*People) ProtoMessage()    {}
func (*People) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d48463eef19a5f, []int{1}
}

func (m *People) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_People.Unmarshal(m, b)
}
func (m *People) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_People.Marshal(b, m, deterministic)
}
func (m *People) XXX_Merge(src proto.Message) {
	xxx_messageInfo_People.Merge(m, src)
}
func (m *People) XXX_Size() int {
	return xxx_messageInfo_People.Size(m)
}
func (m *People) XXX_DiscardUnknown() {
	xxx_messageInfo_People.DiscardUnknown(m)
}

var xxx_messageInfo_People proto.InternalMessageInfo

func (m *People) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *People) GetType() People_PeopleType {
	if m != nil {
		return m.Type
	}
	return People_INTERNAL
}

func (m *People) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *People) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *People) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *People) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type Day struct {
	Start                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Stop                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=stop,proto3" json:"stop,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Day) Reset()         { *m = Day{} }
func (m *Day) String() string { return proto.CompactTextString(m) }
func (*Day) ProtoMessage()    {}
func (*Day) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d48463eef19a5f, []int{2}
}

func (m *Day) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Day.Unmarshal(m, b)
}
func (m *Day) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Day.Marshal(b, m, deterministic)
}
func (m *Day) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Day.Merge(m, src)
}
func (m *Day) XXX_Size() int {
	return xxx_messageInfo_Day.Size(m)
}
func (m *Day) XXX_DiscardUnknown() {
	xxx_messageInfo_Day.DiscardUnknown(m)
}

var xxx_messageInfo_Day proto.InternalMessageInfo

func (m *Day) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Day) GetStop() *timestamp.Timestamp {
	if m != nil {
		return m.Stop
	}
	return nil
}

type Contract struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DetailUrl            string   `protobuf:"bytes,2,opt,name=detailUrl,proto3" json:"detailUrl,omitempty"`
	Status               int32    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Mission              *Mission `protobuf:"bytes,4,opt,name=mission,proto3" json:"mission,omitempty"`
	Contractor           *People  `protobuf:"bytes,5,opt,name=contractor,proto3" json:"contractor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d48463eef19a5f, []int{3}
}

func (m *Contract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contract.Unmarshal(m, b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return xxx_messageInfo_Contract.Size(m)
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Contract) GetDetailUrl() string {
	if m != nil {
		return m.DetailUrl
	}
	return ""
}

func (m *Contract) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Contract) GetMission() *Mission {
	if m != nil {
		return m.Mission
	}
	return nil
}

func (m *Contract) GetContractor() *People {
	if m != nil {
		return m.Contractor
	}
	return nil
}

type Uuid struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Uuid) Reset()         { *m = Uuid{} }
func (m *Uuid) String() string { return proto.CompactTextString(m) }
func (*Uuid) ProtoMessage()    {}
func (*Uuid) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d48463eef19a5f, []int{4}
}

func (m *Uuid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Uuid.Unmarshal(m, b)
}
func (m *Uuid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Uuid.Marshal(b, m, deterministic)
}
func (m *Uuid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Uuid.Merge(m, src)
}
func (m *Uuid) XXX_Size() int {
	return xxx_messageInfo_Uuid.Size(m)
}
func (m *Uuid) XXX_DiscardUnknown() {
	xxx_messageInfo_Uuid.DiscardUnknown(m)
}

var xxx_messageInfo_Uuid proto.InternalMessageInfo

func (m *Uuid) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type IdList struct {
	Ids                  []*Uuid  `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdList) Reset()         { *m = IdList{} }
func (m *IdList) String() string { return proto.CompactTextString(m) }
func (*IdList) ProtoMessage()    {}
func (*IdList) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d48463eef19a5f, []int{5}
}

func (m *IdList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdList.Unmarshal(m, b)
}
func (m *IdList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdList.Marshal(b, m, deterministic)
}
func (m *IdList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdList.Merge(m, src)
}
func (m *IdList) XXX_Size() int {
	return xxx_messageInfo_IdList.Size(m)
}
func (m *IdList) XXX_DiscardUnknown() {
	xxx_messageInfo_IdList.DiscardUnknown(m)
}

var xxx_messageInfo_IdList proto.InternalMessageInfo

func (m *IdList) GetIds() []*Uuid {
	if m != nil {
		return m.Ids
	}
	return nil
}

type S3Object struct {
	Bucketname           string   `protobuf:"bytes,1,opt,name=bucketname,proto3" json:"bucketname,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S3Object) Reset()         { *m = S3Object{} }
func (m *S3Object) String() string { return proto.CompactTextString(m) }
func (*S3Object) ProtoMessage()    {}
func (*S3Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d48463eef19a5f, []int{6}
}

func (m *S3Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S3Object.Unmarshal(m, b)
}
func (m *S3Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S3Object.Marshal(b, m, deterministic)
}
func (m *S3Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S3Object.Merge(m, src)
}
func (m *S3Object) XXX_Size() int {
	return xxx_messageInfo_S3Object.Size(m)
}
func (m *S3Object) XXX_DiscardUnknown() {
	xxx_messageInfo_S3Object.DiscardUnknown(m)
}

var xxx_messageInfo_S3Object proto.InternalMessageInfo

func (m *S3Object) GetBucketname() string {
	if m != nil {
		return m.Bucketname
	}
	return ""
}

func (m *S3Object) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type Files struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Files) Reset()         { *m = Files{} }
func (m *Files) String() string { return proto.CompactTextString(m) }
func (*Files) ProtoMessage()    {}
func (*Files) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d48463eef19a5f, []int{7}
}

func (m *Files) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Files.Unmarshal(m, b)
}
func (m *Files) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Files.Marshal(b, m, deterministic)
}
func (m *Files) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Files.Merge(m, src)
}
func (m *Files) XXX_Size() int {
	return xxx_messageInfo_Files.Size(m)
}
func (m *Files) XXX_DiscardUnknown() {
	xxx_messageInfo_Files.DiscardUnknown(m)
}

var xxx_messageInfo_Files proto.InternalMessageInfo

func (m *Files) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

type File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_41d48463eef19a5f, []int{8}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterEnum("lm.object.People_PeopleType", People_PeopleType_name, People_PeopleType_value)
	proto.RegisterType((*Mission)(nil), "lm.object.Mission")
	proto.RegisterType((*Mission_Institution)(nil), "lm.object.Mission.Institution")
	proto.RegisterType((*Mission_TimeSlot)(nil), "lm.object.Mission.TimeSlot")
	proto.RegisterType((*Mission_TimeSlotsWithSelected)(nil), "lm.object.Mission.TimeSlotsWithSelected")
	proto.RegisterType((*People)(nil), "lm.object.People")
	proto.RegisterType((*Day)(nil), "lm.object.Day")
	proto.RegisterType((*Contract)(nil), "lm.object.Contract")
	proto.RegisterType((*Uuid)(nil), "lm.object.Uuid")
	proto.RegisterType((*IdList)(nil), "lm.object.IdList")
	proto.RegisterType((*S3Object)(nil), "lm.object.S3Object")
	proto.RegisterType((*Files)(nil), "lm.object.Files")
	proto.RegisterType((*File)(nil), "lm.object.File")
}

func init() { proto.RegisterFile("object.proto", fileDescriptor_41d48463eef19a5f) }

var fileDescriptor_41d48463eef19a5f = []byte{
	// 779 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x4f, 0xdb, 0x48,
	0x14, 0xc5, 0xce, 0x97, 0x7d, 0x13, 0x41, 0x18, 0x2d, 0x2b, 0x2b, 0xb0, 0x2c, 0x6b, 0x69, 0xa5,
	0x68, 0x17, 0x4c, 0x1b, 0xfa, 0xd2, 0x3e, 0x15, 0x28, 0x08, 0x24, 0x4a, 0xd1, 0x04, 0xd4, 0xbe,
	0x59, 0x8e, 0x3d, 0x81, 0x69, 0x6c, 0x8f, 0xeb, 0x19, 0x53, 0x21, 0xf5, 0xa9, 0xff, 0xa8, 0x7f,
	0xa8, 0xff, 0xa0, 0xff, 0xa1, 0x9a, 0xf1, 0x57, 0xaa, 0xa4, 0xa8, 0x7d, 0x8a, 0xef, 0x3d, 0x67,
	0xee, 0xd8, 0xe7, 0x9c, 0x1b, 0xe8, 0xb1, 0xc9, 0x7b, 0xe2, 0x0b, 0x27, 0x49, 0x99, 0x60, 0xc8,
	0x0c, 0x23, 0x27, 0x6f, 0x0c, 0xfe, 0xbe, 0x65, 0xec, 0x36, 0x24, 0xfb, 0x0a, 0x98, 0x64, 0xd3,
	0x7d, 0x41, 0x23, 0xc2, 0x85, 0x17, 0x25, 0x39, 0xd7, 0xfe, 0xda, 0x86, 0xce, 0x6b, 0xca, 0x39,
	0x65, 0x31, 0x5a, 0x05, 0x9d, 0x06, 0x96, 0xb6, 0xa3, 0x0d, 0x4d, 0xac, 0xd3, 0x00, 0xbd, 0x84,
	0x2e, 0x8d, 0xb9, 0xa0, 0x22, 0x13, 0x94, 0xc5, 0x96, 0xbe, 0xa3, 0x0d, 0xbb, 0xa3, 0x6d, 0xa7,
	0x9a, 0xee, 0x14, 0x07, 0x9d, 0xf3, 0x9a, 0x85, 0xe7, 0x8f, 0x20, 0x0b, 0x3a, 0x9c, 0xa4, 0xf7,
	0xd4, 0x27, 0x56, 0x43, 0x8d, 0x2d, 0x4b, 0xb4, 0x09, 0xe6, 0xc4, 0xf3, 0x67, 0x6e, 0x48, 0xe3,
	0x99, 0xd5, 0x54, 0x98, 0x21, 0x1b, 0x17, 0x34, 0x9e, 0xa1, 0x5d, 0x40, 0x9e, 0xef, 0x93, 0x44,
	0x90, 0xc0, 0xad, 0x59, 0x2d, 0xc5, 0xea, 0x97, 0xc8, 0x51, 0xc9, 0xfe, 0x0f, 0xd6, 0x53, 0x32,
	0xcd, 0xf8, 0x0f, 0xe4, 0xb6, 0x22, 0xaf, 0x15, 0x40, 0xc5, 0xfd, 0x13, 0xda, 0x11, 0x13, 0xf4,
	0x9e, 0x58, 0x1d, 0x45, 0x28, 0x2a, 0xd9, 0x4f, 0x89, 0xc7, 0x59, 0x6c, 0x19, 0x79, 0x3f, 0xaf,
	0xd0, 0x3e, 0x98, 0x29, 0xf9, 0x90, 0x11, 0x2e, 0x48, 0x6a, 0x99, 0x4a, 0x80, 0xf5, 0x39, 0x01,
	0xae, 0x08, 0x4b, 0x42, 0x82, 0x6b, 0x0e, 0xda, 0x03, 0x74, 0xef, 0x85, 0x34, 0xf0, 0xe4, 0xf7,
	0xbb, 0x3e, 0x8b, 0x22, 0x12, 0x0b, 0x0b, 0xd4, 0xd0, 0xf5, 0x1a, 0x39, 0xce, 0x01, 0xe4, 0x83,
	0x25, 0x1d, 0x71, 0x79, 0xc8, 0x04, 0x77, 0x3f, 0x52, 0x71, 0xe7, 0x72, 0x12, 0x12, 0x5f, 0x90,
	0xc0, 0xea, 0xa9, 0xeb, 0x86, 0x4b, 0xf4, 0xbe, 0xa6, 0x11, 0x19, 0xcb, 0x13, 0x6f, 0xa9, 0xb8,
	0x1b, 0x17, 0xfc, 0xb3, 0x15, 0xbc, 0x21, 0x96, 0x01, 0x83, 0x08, 0xba, 0x73, 0x0e, 0x21, 0x04,
	0xcd, 0xd8, 0x8b, 0x48, 0x61, 0xb4, 0x7a, 0x2e, 0xac, 0xd7, 0x2b, 0xeb, 0xff, 0x02, 0xe0, 0x11,
	0x77, 0x3d, 0x5f, 0x69, 0x25, 0xbd, 0x33, 0xb0, 0xc9, 0x23, 0x7e, 0xa8, 0x1a, 0xd2, 0x3d, 0x09,
	0x27, 0xa9, 0x74, 0x56, 0xba, 0xa7, 0x63, 0x83, 0x47, 0xfc, 0x4a, 0xd6, 0x83, 0x4f, 0x60, 0x94,
	0x2f, 0xb8, 0x10, 0xa9, 0x27, 0xd0, 0xe2, 0xc2, 0x4b, 0x45, 0x11, 0xa6, 0x81, 0x93, 0xe7, 0xd3,
	0x29, 0xf3, 0xa9, 0x3e, 0x4d, 0xe5, 0x13, 0xe7, 0x44, 0xe4, 0x40, 0x93, 0x0b, 0x96, 0xa8, 0x77,
	0x78, 0xfc, 0x80, 0xe2, 0x0d, 0x3e, 0x6b, 0xb0, 0xb1, 0x54, 0x1f, 0xf4, 0x02, 0xa0, 0xd6, 0xda,
	0xd2, 0x76, 0x1a, 0xc3, 0xee, 0x68, 0xf3, 0x11, 0x75, 0xb1, 0x59, 0xc9, 0x89, 0xf6, 0xc0, 0xa8,
	0x7c, 0xd1, 0x7f, 0x16, 0x83, 0x8a, 0x72, 0x64, 0x42, 0xc7, 0x67, 0xb1, 0x20, 0xb1, 0xb0, 0xbf,
	0x69, 0xd0, 0xce, 0xf1, 0x25, 0x62, 0x34, 0xc5, 0x43, 0x42, 0xd4, 0xc0, 0xd5, 0xd1, 0xd6, 0xc2,
	0xc0, 0xe2, 0xe7, 0xfa, 0x21, 0x21, 0x58, 0x31, 0xa5, 0x2d, 0x53, 0x9a, 0x72, 0xe1, 0x2a, 0x03,
	0xf3, 0x95, 0x32, 0x55, 0xe7, 0x52, 0xba, 0xb8, 0x09, 0x66, 0xe8, 0x95, 0x68, 0xb1, 0x54, 0xb2,
	0xa1, 0xc0, 0x3f, 0xa0, 0x45, 0x22, 0x8f, 0x86, 0xc5, 0x1e, 0xe5, 0x85, 0xec, 0x26, 0x77, 0x2c,
	0x26, 0xc5, 0xc2, 0xe4, 0x85, 0xfd, 0x1c, 0xa0, 0xbe, 0x1b, 0xf5, 0xc0, 0x38, 0xbf, 0xbc, 0x3e,
	0xc1, 0x97, 0x87, 0x17, 0xfd, 0x15, 0x59, 0x9d, 0xbc, 0x2b, 0x2a, 0x0d, 0x75, 0xa0, 0x81, 0x6f,
	0xc6, 0xfd, 0x06, 0x6a, 0x83, 0x7e, 0x86, 0xfb, 0x4d, 0xfb, 0x16, 0x1a, 0xaf, 0xbc, 0x87, 0xda,
	0x68, 0xed, 0x77, 0x8d, 0xd6, 0x7f, 0xcd, 0x68, 0xfb, 0x8b, 0x06, 0xc6, 0x31, 0x8b, 0x45, 0xea,
	0xf9, 0x8b, 0x39, 0xdb, 0x02, 0x33, 0x20, 0xc2, 0xa3, 0xe1, 0x4d, 0x1a, 0x16, 0xb1, 0xae, 0x1b,
	0x72, 0xdb, 0xb9, 0xf0, 0x44, 0xc6, 0x95, 0x84, 0x2d, 0x5c, 0x54, 0x68, 0x17, 0x3a, 0x51, 0x1e,
	0x02, 0xa5, 0x5e, 0x77, 0x84, 0x16, 0xe3, 0x81, 0x4b, 0x0a, 0x7a, 0x0a, 0xe0, 0x17, 0xf7, 0xb3,
	0x54, 0xa9, 0xba, 0x34, 0x15, 0x73, 0x24, 0x7b, 0x00, 0xcd, 0x9b, 0x8c, 0x06, 0x72, 0x05, 0xb3,
	0xac, 0x7a, 0x61, 0xf5, 0x6c, 0xff, 0x0f, 0xed, 0xf3, 0xe0, 0x82, 0x72, 0x81, 0xfe, 0x81, 0x06,
	0x0d, 0xca, 0x84, 0xae, 0xcd, 0x4d, 0x94, 0x67, 0xb1, 0xc4, 0xec, 0x53, 0x30, 0xc6, 0x07, 0x6f,
	0x54, 0x17, 0x6d, 0x03, 0x4c, 0x32, 0x7f, 0x46, 0xc4, 0xdc, 0x56, 0xcf, 0x75, 0xd0, 0x00, 0x8c,
	0x29, 0x0d, 0x89, 0x42, 0x73, 0x29, 0xaa, 0xda, 0x76, 0xa0, 0x75, 0x4a, 0x43, 0xc2, 0xd1, 0xbf,
	0xd0, 0x92, 0xcd, 0x65, 0xb7, 0x4a, 0x02, 0xce, 0x51, 0xfb, 0x19, 0x34, 0x65, 0xb9, 0xf4, 0x3f,
	0xc4, 0xaa, 0x42, 0xaf, 0xae, 0xe9, 0xe1, 0xb2, 0x9c, 0xb4, 0x95, 0x89, 0x07, 0xdf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x9d, 0x7d, 0x64, 0x1b, 0xa7, 0x06, 0x00, 0x00,
}
